[custom.all.spidr]
type = "local"
path = ""
ipkg = "spidr/spidr.ipkg"

[custom.all.runner]
type = "local"
path = ""
ipkg = "test/runner.ipkg"

[custom.all.pjrt-plugin-xla-cpu]
type = "local"
path = ""
ipkg = "pjrt-plugins/xla-cpu/pjrt-plugin-xla-cpu.ipkg"

[custom.all.pjrt-plugin-xla-cuda]
type = "local"
path = ""
ipkg = "pjrt-plugins/xla-cuda/pjrt-plugin-xla-cuda.ipkg"
