cc_library(
    name = "c_xla",
    deps = [
        "//src/xla:xla",
        "//src/xla/client:client",
        "//src/xla/client/lib:lib",
        "//src/xla/pjrt:pjrt",
        "//src/xla/pjrt/c:pjrt_c",
        "//src/xla/service:service",
        "//src:src",
    ],
)
