cc_binary(
    name = "c_xla",
    linkshared = True,
    srcs = [
        "//src/xla:xla",
        "//src/xla/client:client",
        "//src/xla/client/lib:lib",
        "//src/xla/service:service",
        "//src/xla/stream_executor:stream_executor",
        "//src/xla/stream_executor/gpu:gpu",
        "//src:src",
    ],
    deps = [
        "//src/xla:xla",
        "//src/xla/client:client",
        "//src/xla/client/lib:lib",
        "//src/xla/service:service",
        "//src/xla/stream_executor:stream_executor",
        "//src/xla/stream_executor/gpu:gpu",
        "//src:src",
    ],
)
