cc_library(
    name = "reference",
    linkstatic = True,
    alwayslink = True,
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    deps = [
        "@stablehlo//:stablehlo_ops",
    ],
    visibility = ["//visibility:public"],
)
