# see runtime/BUILD for why we use `cc_binary`

cc_binary(
    name = "ir",
    linkshared = True,
    linkstatic = True,
    srcs = [
        "//src/stablehlo/stablehlo/reference",
    ],
    deps = [
        "//src/stablehlo/stablehlo/reference",
    ],
)
