on:
  push:
    branches: master
  schedule:
    # maintains a cache on the default branch, available for feature branches to use
    - cron: '0 0 * * *'

jobs:
  xla-linux-cpu:
    runs-on: ubuntu-latest
    container: tensorflow/build:latest-python3.9
    steps:
    - uses: actions/checkout@v4
    - name: Build XLA static Linux CPU
      working-directory: backend
      run: |
        ./install.sh
        ./build.sh
    - name: Free disk space
      uses: jlumbroso/free-disk-space@main
    - name: Save Bazel cache
      uses: actions/cache/save@v4
      with:
        path: ~/.cache/bazel
        key: xla-${{ runner.os }}
