on:
  pull_request:
    branches: master
    paths:
      - 'spidr/backend/**'
      - 'XLA_VERSION'

jobs:
  backend-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Check backend version is updated
      run: sh -c "! git diff --exit-code HEAD^ spidr/backend/VERSION"
