on:
  pull_request:
    branches: master

env:
  PACK_DIR: /root/.pack

jobs:
  test-unit:
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack
    steps:
    - uses: actions/checkout@v3
    - name: Build backend
      working-directory: backend
      run: |
        ./install_bazel.sh
        ./build.sh cpu
    - name: Build tests
      run: |
        pack switch HEAD
        pack --no-prompt build test.ipkg
    - name: Run tests
      run: pack run test.ipkg
      env:
        LD_LIBRARY_PATH: $LD_LIBRARY_PATH:backend/bazel-bin
  readme:
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack
    steps:
    - uses: actions/checkout@v3
    - name: Type-check README
      run: |
        pack switch HEAD
        pack --no-prompt typecheck readme.ipkg
  tutorials:
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack
    steps:
    - uses: actions/checkout@v3
    - name: Type-check tutorials
      run: |
        pack switch HEAD
        res=0; for f in tutorials/*.ipkg; do pack --no-prompt typecheck $f || res=$?; done; $(exit $res)
