# Copyright 2021 Joel Berkeley
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
on:
  pull_request:
    branches: master

env:
  PACK_DIR: /root/.pack

jobs:
  test-unit:
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack
    steps:
    - uses: actions/checkout@v3
    - name: Install Bazel
      run: ./install_c_xla.sh cpu
    - name: Run tests
      run: pack run test.ipkg
      env:
        LD_LIBRARY_PATH: $LD_LIBRARY_PATH:backend/bazel-bin
  readme:
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack
    steps:
    - uses: actions/checkout@v3
    - name: Type-check README
      run: pack typecheck readme.ipkg
  tutorials:
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack
    steps:
    - uses: actions/checkout@v3
    - name: Type-check tutorials
      run: res=0; for f in tutorials/*.ipkg; do pack typecheck $f || res=$?; done; $(exit $res)
  c-xla-cpu:
    env:
      TAR_NAME: c_xla_extension-x86_64-linux-cpu
    runs-on: ubuntu-latest
    steps:
    - name: Build C XLA lib
      uses: actions/checkout@v3
    - working-directory: backend
      run: |
        ./build.sh cpu
        DIR=$(mktemp -d)
        mkdir -p $DIR/$TAR_NAME/lib
        mv bazel-bin/libc_xla_extension.so $DIR/$TAR_NAME/lib
        tar cfz $TAR_NAME.tar.gz -C $DIR .
    - name: Create C XLA release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: c-xla-${{ github.sha }}
        release_name: C XLA release ${{ github.sha }}
    - name: Upload C XLA lib
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: backend/${{ env.TAR_NAME }}.tar.gz
        asset_name: ${{ env.TAR_NAME }}.tar.gz
        asset_content_type: application/gzip
  c-xla-gpu:
    env:
      TAR_NAME: c_xla_extension-x86_64-linux-cuda111
    runs-on: ubuntu-latest
    steps:
      - name: Build C XLA lib
        uses: actions/checkout@v3
    - working-directory: backend
      run: |
        ./build.sh cuda111
        DIR=$(mktemp -d)
        mkdir -p $DIR/$TAR_NAME/lib
        mv bazel-bin/libc_xla_extension.so $DIR/$TAR_NAME/lib
        tar cfz $TAR_NAME.tar.gz -C $DIR .
    - name: Create C XLA release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: c-xla-${{ github.sha }}
        release_name: C XLA release ${{ github.sha }}
    - name: Upload C XLA lib
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: backend/${{ env.TAR_NAME }}.tar.gz
        asset_name: ${{ env.TAR_NAME }}.tar.gz
        asset_content_type: application/gzip
