# Copyright 2021 Joel Berkeley
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
on:
  pull_request:
    branches: master
    paths-ignore: 'README.md'

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install idris2
        wget -qO- https://github.com/elixir-nx/xla/releases/download/v0.2.0/xla_extension-x86_64-linux-cpu.tar.gz | tar xvz -C backend/

        sudo apt install -y apt-transport-https curl gnupg
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
        sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt update && sudo apt install bazel

        cd backend
        BAZEL_CXXOPTS='-std=c++14' bazel build //:c_xla_extension
        cd -
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/backend/bazel-bin

        idris2 --install spidr.ipkg
        idris2 -p spidr test/Tensor.idr -o test
        ./build/exec/test
  tutorials:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install idris2
        idris2 --install spidr.ipkg
        res=0; for f in tutorials/*.md; do idris2 --check "$f" || res=$?; done; $(exit $res)
