on:
  pull_request:
    branches: master

jobs:
  pjrt-hlo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check PJRT/HLO libs version is updated when necessary
        run: |
          sh -c "
          (git diff --quiet HEAD^ XLA_VERSION && git diff --quiet HEAD^ spidr/backend/**) || \
            ! git diff --quiet HEAD^ spidr/backend/VERSION
          "
  pjrt-xla-cpu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check PJRT XLA CPU plugin version is updated when necessary
        run: |
          sh -c "
          (git diff --quiet HEAD^ XLA_VERSION && git diff --quiet HEAD^ pjrt-plugins/xla-cpu/**) || \
            ! git diff --quiet HEAD^ pjrt-plugins/xla-cpu/VERSION
          "
      - name: Check PJRT XLA CPU plugin versions are equal
        working-directory: pjrt-plugins/xla-cpu
        run: grep -Fx "version = $(cat VERSION)" pjrt-plugin-xla-cpu.ipkg
  pjrt-xla-cuda:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check PJRT XLA CUDA plugin version is updated when necessary
        run: |
          sh -c "
          (git diff --quiet HEAD^ XLA_VERSION && git diff --quiet HEAD^ pjrt-plugins/xla-cuda/**) || \
            ! git diff --quiet HEAD^ pjrt-plugins/xla-cuda/VERSION
          "
      - name: Check PJRT XLA CUDA plugin versions are equal
        working-directory: pjrt-plugins/xla-cuda
        run: grep -Fx "version = $(cat VERSION)" pjrt-plugin-xla-cuda.ipkg
