on:
  pull_request:
    branches: master

jobs:
  versioning:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check PJRT/HLO libs version is updated when necessary
        run: |
          sh -c "
          (git diff --quiet HEAD^ XLA_VERSION && git diff --quiet HEAD^ spidr/backend/**) || \
            ! git diff --quiet HEAD^ spidr/backend/VERSION
          "
      - name: Check PJRT XLA CPU plugin versions are equal
        working-directory: pjrt-plugins/xla-cpu
        run: |
          sh -c "grep -Fx \"version = $(cat VERSION)\" pjrt-plugin-xla-cpu.ipkg"
      - name: Check PJRT XLA CUDA plugin versions are equal
        working-directory: pjrt-plugins/xla-cuda
        run: |
          sh -c "grep -Fx \"version = $(cat VERSION)\" pjrt-plugin-xla-cuda.ipkg"
