on:
  pull_request:
    branches: master
    paths:
      - 'spidr/backend/**'

jobs:
  backend-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Check backend version is updated
      run: if [[ -z $(git diff HEAD~1 spidr/backend/VERSION) ]]; then exit 1; fi
